sudo: required
services:
  - docker
before_install:
  - docker build -t shinethroughtrees/test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shinethroughtrees/test npm test -- --coverage

after_success:
  - docker build -t lim6112j/multi-client ./client
  - docker build -t lim6112j/multi-nginx ./nginx
  - docker build -t lim6112j/multi-server ./server
  - docker build -t lim6112j/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push image to docker hub
  - docker push lim6112j/multi-client
  - docker push lim6112j/multi-nginx
  - docker push lim6112j/multi-server
  - docker push lim6112j/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-103975427298
  "
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
